apiVersion: v1
kind: Service
metadata:
  name: complaint-frontend
  labels:
    app: complaint-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: complaint-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
