apiVersion: v1
kind: Service
metadata:
  name: complaint-service
  labels:
    app: complaint-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: complaint-service
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
